
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Christos Ziskas"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "2351023123"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

  { 
    "name": "Arto Hellas", 
    "number": "040-123456"
  }