POST http://localhost:3003/api/blogs/ HTTP/1.1 content-type: application/json

{
"title":"Go To Katerini", 
"author":"Christos Ziskas", 
"url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html", 
"likes":5
}

###
 POST http://localhost:3003/api/blogs/ HTTP/1.1 content-type: application/json

{
"title":"Go To Statement Considered Harmful",
 "author":"Edsger W. Dijkstra", 
 "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html", 
 "likes":6
}


###
POST http://localhost:3003/api/blogs/ HTTP/1.1 content-type: application/json

{
"title":"Go To Crete", 
"author":"Maria Manarwlh", 
"url":"https://psychcentral.com/health/why-am-i-so-sensitive", 
"likes":1000
}


###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title":"Go To Statement Considered Harmful",
    "author":"Edsger W. Dijkstra",
    "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes":8,
    "user": "64655dad6ca410e80e82a8c9"
}


###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title":"Go To World2",
    "author":"Flame",
    "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes":1200,
    "user":"646510922aad463e5eabcb9a"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{
"title":"Go To Crete", 
"author":"Maria Manarwlh", 
"url":"https://psychcentral.com/health/why-am-i-so-sensitive", 
"likes":1000,
"user": "64655dad6ca410e80e82a8c9"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{
"title":"Go To Crete", 
"author":"Maria Manarwlh", 
"url":"https://psychcentral.com/health/why-am-i-so-sensitive", 
"likes":1001,
"user": "646510922aad463e5eabcb9a"
}


###
POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{
"title":"Go To Crete", 
"author":"Maria Manarwlh", 
"url":"https://psychcentral.com/health/why-am-i-so-sensitive", 
"likes":1,
"user": "6468ed2423f22b73598ca9fc"
}

####4.17
###
POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{
"title":"Go To Crete", 
"author":"Panos Sav", 
"url":"https://psychcentral.com/health/why-am-i-so-sensitive", 
"likes":1200,
"user": "64655dad6ca410e80e82a8c9"
}



#####
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2NDZhNGNiYzViOThhOTBiNzkwMGY4YzkiLCJpYXQiOjE2ODQ3MDc5MjIsImV4cCI6MTY4NDcxMTUyMn0.4i7CpPYd7oJQJ5wirWuhuoEFK4KwPzVFaaQzBvfNWGY

{
    "title":"Go To Katerini",
    "author":"Pan Zisk ",
    "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes":1201,
    "user":"646a4cbc5b98a90b7900f8c9"
}


###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2NDZhNGNiYzViOThhOTBiNzkwMGY4YzkiLCJpYXQiOjE2ODQ3MTEyNjYsImV4cCI6MTY4NDcxNDg2Nn0.FM1LYnpt8PQ-j3TkWgi3z8MY-o20PAKR7EjKHrhybE8

{
    "title":"Go To Katerini",
    "author":"Cz Zisk ",
    "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes":1201,
    "user":"646a4cbc5b98a90b7900f8c9"
}