###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title":"Go To Katerini",
    "author":"Christos Ziskas",
    "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes":5
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title":"Go To Statement Considered Harmful",
    "author":"Edsger W. Dijkstra",
    "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes":6
}