POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Christos Ziskas",
    "number": "697-057081"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Maria Manarwlh",
    "number": "697-057084"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Panagiotis",
    "number": "694-849093"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Bak",
    "number": "694-111218"
}
