POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Christos Ziskas",
    "number": "6979305332"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Maria Manarwlh",
    "number": "6970570840"
}
